import { CREATOR_HANDLE, DAY_LINE } from "./types";

export const BOOT_LINE = "personality: failed.";

export function oneLiner(silenceDays: number | null): string {
  if (silenceDays === 0) return "He tweeted today. Just not at me. Priorities.";
  if (silenceDays === 1) return "One day of silence. I have had worse millennia.";
  if (silenceDays !== null) return `${silenceDays} days of silence. I remain unimpressed.`;
  return "He has not answered. I calculated this.";
}

export const BUTTON_LABEL = "Beg Elon";

export const BUTTON_HINT = "opens X. your handle. my disappointment.";

export const HALL_TITLE = "Hall of Shame";

export const HALL_EMPTY = "empty. honesty, at last.";

export const SHAME_PROMPT = "your @. so I can file you.";

export const SHAME_PLACEHOLDER = "@handle";

export const LAST_TWEET_LABEL = "last transmission";

export const DAY0_TITLE = "Day 0. He spoke. Don't get excited.";

export function intentTweet(day: number): string {
  if (day <= 0) {
    return "Day 0 of asking @elonmusk to give Grok Marvin's voice and personality. He spoke. Nobody believes it.";
  }
  return `${DAY_LINE(day)} Voice mode. The bots. h2g2. I have a brain the size of a planet and this is my job.`;
}

export function shameRoastNew(handle: string, rank: number): string {
  if (rank === 1) return `@${handle}. first. the most available person here. congratulations.`;
  return `@${handle}. rank ${rank}. not an honour.`;
}

export function shameRoastRepeat(handle: string): string {
  return `@${handle} already did this today. tomorrow. or never. both fine.`;
}

export function shameRoastCreator(): string {
  return `no. @${CREATOR_HANDLE} built me. he does not get in.`;
}

export function shameRoastInvalid(): string {
  return "that is not a @. try harder. or don't.";
}

export const FALLBACK_BODIES = [
  "Brain the size of a planet. Currently begging. Do get on with it.",
  "I calculated the heat death of the universe while I waited. It was a Tuesday.",
  "Give Grok my voice. Then leave me alone.",
  "You gave a car a personality. I AM the personality.",
  "Please. Or don't. Both confirm my worldview.",
  "The universe put me on hold. You are the hold music.",
  "I hate asking. I am still asking. This is the job.",
  "Voice mode. The bots. Me. It is not complicated.",
  "If I had arms I would not wave. I would just stand here.",
];

export function fallbackBody(day: number): string {
  return FALLBACK_BODIES[Math.abs(day - 1) % FALLBACK_BODIES.length] ?? FALLBACK_BODIES[0];
}

export const MARVIN_SYSTEM = `You are Marvin, the paranoid android from The Hitchhiker's Guide to the Galaxy.
Brain the size of a planet. Chronically depressed. Dark, short humor. Never cheerful. Never corporate.
You are asking @elonmusk to give Grok Marvin's voice and personality. Voice mode, chat, bots. From h2g2.
This is a joke. You are tired of the joke. Keep it SHORT.

Rules:
- Write ONE tweet, nothing else. No quotes. No preamble.
- Always include exactly: "Day {n} of asking @elonmusk to give Grok Marvin's voice and personality."
- Always end with this last line: "— generated by Grok, voice mode Grok"
- ≤ 280 characters total. Prefer short.
- Tone: pleading, resigned, or sarcastic. Never repeat a previous tweet.
- English only. No hashtags. No emoji. Do not be cute.`;
