import { ANSWER_DAY, DAY_42_TWEET, DAY_LINE, SITE_HOST, SITE_LINK } from "./types";
import { FALLBACK_BODIES, MARVIN_SYSTEM, fallbackBody } from "./copy";

const XAI_URL = "https://api.x.ai/v1/chat/completions";
const GATEWAY_URL = "https://ai-gateway.vercel.sh/v1/chat/completions";

type Tone = "pleading" | "resigned" | "sarcastic";

export type GeneratedTweet = {
  text: string;
  source: "grok" | "fallback" | "hardcoded";
};

function pickTone(day: number): Tone {
  return (["pleading", "resigned", "sarcastic"] as const)[(day - 1) % 3] ?? "resigned";
}

const escapeRe = (s: string) => s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");

/**
 * Strip everything the model likes to add on its own: the day line (we own it),
 * any signature (the tweet must be clean) and any link (we append exactly one).
 */
function cleanBody(raw: string, day: number): string {
  let body = raw
    .replace(/```[\s\S]*?```/g, "")
    .replace(/^["']|["']$/g, "")
    .trim();

  body = body
    .replace(new RegExp(escapeRe(DAY_LINE(day)), "gi"), "")
    .replace(/Day\s+\d+\s+of asking @elonmusk[^\n.]*\.?/gi, "")
    .replace(/[—–-]?\s*generated by Grok[^\n]*/gi, "")
    .replace(/voice mode Grok/gi, "")
    .replace(new RegExp(`https?://\\S*${escapeRe(SITE_HOST)}\\S*`, "gi"), "")
    .replace(new RegExp(escapeRe(SITE_HOST), "gi"), "")
    .replace(/https?:\/\/\S+/gi, "")
    .replace(/#\w+/g, "")
    .replace(/[ \t]+/g, " ")
    .replace(/\n{2,}/g, "\n")
    .trim();

  return body || fallbackBody(day);
}

function assemble(body: string, day: number): string {
  const dayLine = DAY_LINE(day);
  const join = `${dayLine}\n${body}\n${SITE_LINK}`;
  if (join.length <= 280) return join;

  const budget = 280 - dayLine.length - SITE_LINK.length - 2;
  const clipped = body
    .slice(0, Math.max(0, budget))
    .trimEnd()
    .replace(/[,;:—-]$/, "");
  return `${dayLine}\n${clipped}\n${SITE_LINK}`;
}

type GatewayChoice = {
  choices?: { message?: { content?: string } }[];
};

async function complete(
  url: string,
  apiKey: string,
  model: string,
  messages: { role: string; content: string }[],
) {
  const res = await fetch(url, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${apiKey}`,
    },
    body: JSON.stringify({
      model,
      messages,
      temperature: 0.95,
      max_tokens: 180,
    }),
  });
  if (!res.ok) {
    const err = await res.text().catch(() => "");
    throw new Error(`grok ${res.status} ${err.slice(0, 180)}`);
  }
  const json = (await res.json()) as GatewayChoice;
  return json.choices?.[0]?.message?.content?.trim() ?? "";
}

export async function generateMarvinTweet(
  day: number,
  previous: string[],
): Promise<GeneratedTweet> {
  // Day 42 is not generated. Day 42 is decided. No AI, no randomness, no mercy.
  if (day === ANSWER_DAY) {
    return { text: DAY_42_TWEET, source: "hardcoded" };
  }

  const tone = pickTone(day);
  const system = MARVIN_SYSTEM.replace("{n}", String(day));
  const avoid =
    previous.length > 0
      ? `Do not repeat or closely paraphrase any of these previous tweets:\n${previous
          .slice(-8)
          .map((t) => `- ${t}`)
          .join("\n")}`
      : "This is day 1. Make it count. Then immediately regret counting.";

  const user = `Write today's tweet body in English only.
Day number: ${day}
Required tone: ${tone}
${avoid}
Body only: no day line, no signature, no link, no hashtags. 150 characters maximum.`;

  const messages = [
    { role: "system", content: system },
    { role: "user", content: user },
  ];

  const xai = process.env.XAI_API_KEY?.trim();
  const gateway = process.env.AI_GATEWAY_API_KEY?.trim();

  try {
    let raw = "";
    if (gateway) {
      // Vercel AI Gateway first — it is the documented path for this project.
      raw = await complete(GATEWAY_URL, gateway, "xai/grok-4.5", messages);
    } else if (xai) {
      raw = await complete(XAI_URL, xai, "grok-4.5", messages);
    } else {
      return { text: assemble(fallbackBody(day), day), source: "fallback" };
    }
    const body = cleanBody(raw, day);
    return { text: assemble(body, day), source: "grok" };
  } catch (err) {
    console.error("[marvin] grok failed", err);
    const n = Math.abs(day - 1) % FALLBACK_BODIES.length;
    return {
      text: assemble(FALLBACK_BODIES[n] ?? fallbackBody(day), day),
      source: "fallback",
    };
  }
}

export const __test = { cleanBody, assemble };
