import { DAY_LINE, TWEET_SIGNATURE } from "./types";
import { FALLBACK_BODIES, MARVIN_SYSTEM, fallbackBody } from "./copy";

const XAI_URL = "https://api.x.ai/v1/chat/completions";
const GATEWAY_URL = "https://ai-gateway.vercel.sh/v1/chat/completions";

type Tone = "pleading" | "resigned" | "sarcastic";

function pickTone(day: number): Tone {
  return (["pleading", "resigned", "sarcastic"] as const)[(day - 1) % 3] ?? "resigned";
}

function clipTweet(raw: string, day: number): string {
  const dayLine = DAY_LINE(day);
  const sig = TWEET_SIGNATURE;
  let body = raw
    .replace(/^```[\s\S]*?```$/g, "")
    .replace(/^["']|["']$/g, "")
    .trim();

  body = body
    .replace(new RegExp(dayLine.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"), "gi"), "")
    .replace(/Day\s+\d+\s+of asking @elonmusk to give Grok Marvin's voice and personality\.?/gi, "")
    .replace(/Day\s+\d+\s+of asking @elonmusk to give Marvin from h2g2\.?/gi, "")
    .replace(/Day\s+\d+\s+of asking @elonmusk to GIVE MARVIN\.?/gi, "")
    .replace(/— generated by Grok, voice mode Grok/gi, "")
    .replace(/^generated by Grok.*$/gim, "")
    .trim();

  if (!body) body = fallbackBody(day);

  const join = `${dayLine}\n${body}\n${sig}`;
  if (join.length <= 280) return join;

  const budget = 280 - dayLine.length - sig.length - 2;
  const clipped = body.slice(0, Math.max(0, budget)).trimEnd();
  return `${dayLine}\n${clipped}\n${sig}`;
}

type GatewayChoice = {
  choices?: { message?: { content?: string } }[];
};

async function complete(url: string, apiKey: string, model: string, messages: { role: string; content: string }[]) {
  const res = await fetch(url, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${apiKey}`,
    },
    body: JSON.stringify({
      model,
      messages,
      temperature: 0.95,
      max_tokens: 180,
    }),
  });
  if (!res.ok) {
    const err = await res.text().catch(() => "");
    throw new Error(`grok ${res.status} ${err.slice(0, 180)}`);
  }
  const json = (await res.json()) as GatewayChoice;
  return json.choices?.[0]?.message?.content?.trim() ?? "";
}

export async function generateMarvinTweet(
  day: number,
  previous: string[],
): Promise<{ text: string; source: "grok" | "fallback" }> {
  const tone = pickTone(day);
  const system = MARVIN_SYSTEM.replace("{n}", String(day));
  const avoid =
    previous.length > 0
      ? `Do not repeat or closely paraphrase any of these previous tweets:\n${previous
          .slice(-8)
          .map((t) => `- ${t}`)
          .join("\n")}`
      : "This is day 1. Make it count. Then immediately regret counting.";

  const user = `Write today's tweet in English only.
Day number: ${day}
Required tone: ${tone}
${avoid}
Remember the 280 character limit including the Day line and the signature. No French.`;

  const messages = [
    { role: "system", content: system },
    { role: "user", content: user },
  ];

  const xai = process.env.XAI_API_KEY?.trim();
  const gateway = process.env.AI_GATEWAY_API_KEY?.trim();

  try {
    let raw = "";
    if (xai) {
      raw = await complete(XAI_URL, xai, "grok-4.5", messages);
    } else if (gateway) {
      raw = await complete(GATEWAY_URL, gateway, "xai/grok-4.5", messages);
    } else {
      return { text: clipTweet(fallbackBody(day), day), source: "fallback" };
    }
    const text = clipTweet(raw, day);
    // If Grok ignored the shape, still return a valid tweet.
    if (!text.toLowerCase().includes("marvin") || !text.includes(TWEET_SIGNATURE)) {
      return { text: clipTweet(raw || fallbackBody(day), day), source: "grok" };
    }
    return { text, source: "grok" };
  } catch (err) {
    console.error("[marvin] grok failed", err);
    const n = Math.abs(day - 1) % FALLBACK_BODIES.length;
    return { text: clipTweet(FALLBACK_BODIES[n] ?? fallbackBody(day), day), source: "fallback" };
  }
}
