import assert from "node:assert/strict";
import test from "node:test";
import { DAY_42_TWEET, composeTweet, fallbackBody, intentTweet } from "./copy.ts";
import { generateMarvinTweet } from "./grok.ts";
import { DAY_LINE, SITE_URL } from "./types.ts";

/** No Grok key in the test env, so the generator takes its fallback path. */
delete process.env.XAI_API_KEY;
delete process.env.AI_GATEWAY_API_KEY;

test("every tweet opens with the day line and closes with the site link", () => {
  const tweet = composeTweet(9, "brain the size of a planet, still here");
  const lines = tweet.split("\n");
  assert.equal(lines[0], DAY_LINE(9));
  assert.equal(lines.at(-1), SITE_URL);
  assert.ok(tweet.length <= 280);
});

test("the Grok signature never comes back", async () => {
  for (const day of [1, 7, 41, 43, 100]) {
    const { text } = await generateMarvinTweet(day, []);
    assert.doesNotMatch(text, /generated by/i, `day ${day} carries a signature`);
    assert.doesNotMatch(text, /voice mode Grok/i, `day ${day} carries a signature`);
    assert.ok(text.startsWith(DAY_LINE(day)), `day ${day} lost the intro`);
    assert.ok(text.endsWith(SITE_URL), `day ${day} lost the site link`);
    assert.ok(text.length <= 280, `day ${day} is ${text.length} chars`);
  }
});

test("day 42 is hardcoded, identical every time, and skips the generator", async () => {
  const runs = await Promise.all(
    [1, 2, 3].map(() => generateMarvinTweet(42, ["anything", "else"])),
  );
  for (const run of runs) {
    assert.equal(run.source, "day42");
    assert.equal(run.text, `${DAY_42_TWEET}\n${SITE_URL}`);
  }
  assert.equal(new Set(runs.map((r) => r.text)).size, 1, "day 42 must not vary");
  assert.match(runs[0]!.text, /The answer to everything is 42/);
  assert.ok(runs[0]!.text.length <= 280);
});

test("the intent tweet matches day 42 too, so the button cannot drift", () => {
  assert.equal(intentTweet(42), `${DAY_42_TWEET}\n${SITE_URL}`);
  assert.equal(intentTweet(5), composeTweet(5, fallbackBody(5)));
});

test("a punchline long enough to overflow gets clipped, not the day line or link", async () => {
  const { text } = await generateMarvinTweet(7, []);
  assert.ok(text.startsWith(DAY_LINE(7)));
  assert.ok(text.endsWith(SITE_URL));
});
