export const CREATOR_HANDLE = "MajorBaguette";
export const ELON_HANDLE = "elonmusk";
export const SITE_HOST = "givemarvin.lol";
export const STATE_BLOB_PATH = "marvin-state.json";

export const DAY_LINE = (n: number) =>
  `Day ${n} of asking @elonmusk to give Grok Marvin's voice and personality.`;

export const TWEET_SIGNATURE = "— generated by Grok, voice mode Grok";

export type CampaignMode = "counting" | "day0";

export type StoredTweet = {
  text: string;
  day: number;
  id: string | null;
  url: string | null;
  postedAt: string;
  postedToX: boolean;
};

export type ShameEntry = {
  handle: string;
  clicks: number;
  firstAt: string;
  lastAt: string;
  lastClickDay: string;
};

export type MarvinState = {
  day: number;
  mode: CampaignMode;
  startedAt: string;
  lastCronAt: string | null;
  lastCronDay: string | null;
  lastTweet: StoredTweet | null;
  tweetIds: string[];
  elonLastTweetAt: string | null;
  elonRepliedAt: string | null;
  hallOfShame: ShameEntry[];
};

export type PublicState = {
  day: number;
  mode: CampaignMode;
  lastTweet: {
    text: string;
    day: number;
    postedAt: string | null;
    url: string | null;
    postedToX: boolean;
  } | null;
  silenceDays: number | null;
  elonLastTweetAt: string | null;
  hallOfShame: { handle: string; clicks: number; lastAt: string }[];
  startedAt: string;
};

export type ShameResult =
  | { ok: true; state: PublicState; roast: string }
  | { ok: false; error: string; roast: string };
