/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as OgRouteImport } from './routes/og'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ApiCronRouteImport } from './routes/api/cron'
import { Route as ApiOgRouteImport } from './routes/api/og'
import { Route as ApiShameRouteImport } from './routes/api/shame'
import { Route as ApiSighRouteImport } from './routes/api/sigh'
import { Route as ApiStateRouteImport } from './routes/api/state'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const OgRoute = OgRouteImport.update({
  id: '/og',
  path: '/og',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronRoute = ApiCronRouteImport.update({
  id: '/api/cron',
  path: '/api/cron',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgRoute = ApiOgRouteImport.update({
  id: '/api/og',
  path: '/api/og',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShameRoute = ApiShameRouteImport.update({
  id: '/api/shame',
  path: '/api/shame',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSighRoute = ApiSighRouteImport.update({
  id: '/api/sigh',
  path: '/api/sigh',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStateRoute = ApiStateRouteImport.update({
  id: '/api/state',
  path: '/api/state',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/og': typeof OgRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/cron': typeof ApiCronRoute
  '/api/og': typeof ApiOgRoute
  '/api/shame': typeof ApiShameRoute
  '/api/sigh': typeof ApiSighRoute
  '/api/state': typeof ApiStateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/og': typeof OgRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/cron': typeof ApiCronRoute
  '/api/og': typeof ApiOgRoute
  '/api/shame': typeof ApiShameRoute
  '/api/sigh': typeof ApiSighRoute
  '/api/state': typeof ApiStateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/og': typeof OgRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/cron': typeof ApiCronRoute
  '/api/og': typeof ApiOgRoute
  '/api/shame': typeof ApiShameRoute
  '/api/sigh': typeof ApiSighRoute
  '/api/state': typeof ApiStateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/og'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/cron'
    | '/api/og'
    | '/api/shame'
    | '/api/sigh'
    | '/api/state'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/og'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/cron'
    | '/api/og'
    | '/api/shame'
    | '/api/sigh'
    | '/api/state'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/og'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/cron'
    | '/api/og'
    | '/api/shame'
    | '/api/sigh'
    | '/api/state'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  OgRoute: typeof OgRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiCronRoute: typeof ApiCronRoute
  ApiOgRoute: typeof ApiOgRoute
  ApiShameRoute: typeof ApiShameRoute
  ApiSighRoute: typeof ApiSighRoute
  ApiStateRoute: typeof ApiStateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og': {
      id: '/og'
      path: '/og'
      fullPath: '/og'
      preLoaderRoute: typeof OgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron': {
      id: '/api/cron'
      path: '/api/cron'
      fullPath: '/api/cron'
      preLoaderRoute: typeof ApiCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og': {
      id: '/api/og'
      path: '/api/og'
      fullPath: '/api/og'
      preLoaderRoute: typeof ApiOgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shame': {
      id: '/api/shame'
      path: '/api/shame'
      fullPath: '/api/shame'
      preLoaderRoute: typeof ApiShameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sigh': {
      id: '/api/sigh'
      path: '/api/sigh'
      fullPath: '/api/sigh'
      preLoaderRoute: typeof ApiSighRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/state': {
      id: '/api/state'
      path: '/api/state'
      fullPath: '/api/state'
      preLoaderRoute: typeof ApiStateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  OgRoute: OgRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiCronRoute: ApiCronRoute,
  ApiOgRoute: ApiOgRoute,
  ApiShameRoute: ApiShameRoute,
  ApiSighRoute: ApiSighRoute,
  ApiStateRoute: ApiStateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
